### ISSUE TITLE
Cmdlets for registering/unregistering licenses would be really nice!

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#144]
Does it make sense that we'd add specific commands just for activation?

- [ ] `Register-UnityLicense -Credentials <Credentials> -Serial <Serial>`
- [x] `Get-UnityLicense`
- [ ] `Unregister-UnityLicense`

**Comment by StephenHodgson** [comment]
Does it make sense that we'd add specific commands just for activation?

- [ ] `Active-UnityLicense -Credentials <Credentials> -Serial <Serial>`
- [x] `Get-UnityLicense`
- [ ] `Return-UnityLicense`

**Comment by Ziugy** [comment]
This makes sense to me. We should follow the PowerShell verbs for commands: https://docs.microsoft.com/en-us/powershell/developer/cmdlet/approved-verbs-for-windows-powershell-commands

Perhaps the Data Verbs Import / Export, or the Lifecycle Verbs Enable / Disable, Install / Uninstall, or Register / Unregister.

**Comment by StephenHodgson** [comment]
Updated :)

**Comment by StephenHodgson** [comment]
Okay we didn't need the `-nographics` arg anyway. I was doing it wrong. But I'd still like to add these specific commands to make it easy.
