### ISSUE TITLE
Start-UnityEditor doesn't have the option to specify additional arguments

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/unitysetup.powershell#145]
Start-UnityEditor should let the user specify additional arguments for the unity command line as not every argument is surfaced to the parameter list of the command.

For example:
```
Start-UnityEditor -BatchMode -AdditionalArgs "-nographics -force-driver-type-warp"
```

**Comment by Ziugy** [comment]
Maybe we could achieve these additional arguments with [splatting](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_splatting?view=powershell-6)?
