### ISSUE TITLE
Start-UnityEditor should print the command line used for invoking Unity

### ISSUE THREAD

**Issue by ForrestTrepte** [Microsoft/unitysetup.powershell#160]
It would be nice to see in a log file exactly what happened. For example, if something isn't working the way you'd expect this output could be used to see the exact command that was run. In a complex script, this could be useful if you want to just reproduce the Unity execution part in isolation.

This should probably be optional or verbose output in case folks *don't* want this in their logs.

**Comment by StephenHodgson** [comment]
Depends, I wouldn't want my username, password, and serial number displayed if it happened to throw an error or something.

**Comment by jwittner** [comment]
I was just wishing for this as well. As a work around, all arguments are printed at the top of your unity log file.

**Comment by jwittner** [comment]
Actually, just verified that the cmd and args, explicitly minus the password and serial are printed in the verbose stream. Its a part of the ShouldProcess support that Start-UnityEditor implements.
