### ISSUE TITLE
Take advantage of the new modules.json at editor path root

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#172]
With some of the newer versions of the editor, there's now a [`modules.json`](https://gist.github.com/StephenHodgson/946f58ecc5398acc14ef364f9b6b32e5) file that defines each modules download location and if they're enabled (`selected`).

`Find-UnitySetupInstaller` is a great candidate for this.

**Comment by jwittner** [comment]
Thinking on this further, it seems like you'd have to have versions of Unity installed already to use this in `Find-UnitySetupInstaller` right? 

Thanks for the contribution for using this with `Get-UnitySetupInstance` =).

Wondering if we can close this if we can't find a way to leverage modules.json within `Find-UnitySetupInstaller`.

**Comment by StephenHodgson** [comment]
I think as long as we find the main editor installer, it could be a post step?

Yeah it doesn't make much sense bc we don't have the editor installed yet, huh?

Well we could def take advantage of it when updating already existing installations.

**Comment by jwittner** [comment]
Closing unless this is holding us back from anything.
