### ISSUE TITLE
Path no longer has trailing \

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#173]
#171 Introduced a new way to search for valid editor instances and used to return a path like:

```
C:\Program Files\Unity\Hub\Editor\2018.3.13f1\
```

But now returns the path:

```
C:\Program Files\Unity\Hub\Editor\2018.3.13f1
```

This is a breaking change from the previous behavior.

**Comment by jwittner** [comment]
Closing as won't fix, unless there's strong justification to force the trailing slash.

**Comment by StephenHodgson** [comment]
I'd just make sure to note it as a breaking change in the release docs
