### ISSUE TITLE
BITS transfer terminates early during Install-UnitySetupInstance

### ISSUE THREAD

**Issue by mister-liss** [microsoft/unitysetup.powershell#184]
The bits transfer seems to end prematurely and then the following errors are printed because the installation attempts to proceed.

Start-BitsTransfer : The job was paused because there is an active Game Mode recipient that isn't the job's owner. The
job will resume once the Game Mode recipient loses input focus or is closed.
At C:\Users\stlis\Documents\WindowsPowerShell\Modules\UnitySetup\4.0.97\UnitySetup.psm1:472 char:13
+             Start-BitsTransfer -Source $downloadSource -Destination $ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBits
   TransferCommand

Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\stlis\Documents\WindowsPowerShell\Modules\UnitySetup\4.0.97\UnitySetup.psm1:487 char:24
+             $process = Start-Process @startProcessArgs
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\stlis\Documents\WindowsPowerShell\Modules\UnitySetup\4.0.97\UnitySetup.psm1:487 char:24
+             $process = Start-Process @startProcessArgs
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At C:\Users\stlis\Documents\WindowsPowerShell\Modules\UnitySetup\4.0.97\UnitySetup.psm1:487 char:24
+             $process = Start-Process @startProcessArgs
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

Repeating the command allows the bits transfer to finish and completes the installation.

**Comment by Ziugy** [comment]
You're on an earlier version of UnitySetup. BITS has been removed in favor of alternative platform solutions. Are you able to update to release 5.0?

**Comment by mister-liss** [comment]
Got the latest version and all is good. Thanks.
