### ISSUE TITLE
Android support modules

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/unitysetup.powershell#207]
Question, are we also downloading and installing the Android support modules for the sdk/ndk?

**Comment by jwittner** [comment]
[Looks like](https://github.com/microsoft/unitysetup.powershell/blob/aa70e5e9c6af74e12d80888bb24efab2c1491965/UnitySetup/UnitySetup.psm1#L383) the only thing we search for is: `"$targetSupport/UnitySetup-Android-Support-for-Editor-$Version.$installerExtension"` so I suspect not.

**Comment by StephenHodgson** [comment]
Ah okay I thought so bc the hosted machines got updated and now Android builds are failing bc it find the Android SDK and NDK

**Comment by akiojin** [comment]
I get a timeout and a build error during installation while waiting for the NDK license to be entered.

**Comment by bdovaz** [comment]
Any news on this?

**Comment by jwittner** [comment]
Not that I know of. Open to PRs though. =)

**Comment by khayamgondal** [comment]
Any update on this? My project needs NDK to build :(
