### ISSUE TITLE
Error installing Unity Version - 2020.X.X

### ISSUE THREAD

**Issue by qelu** [microsoft/unitysetup.powershell#219]
Good afternoon,

I am experiencing an issue where I am getting an error every time I try to install a 2020 version of Unity (ex. 2020.2.1f1)

I've runned the following commands:

```
$Installers = Find-UnitySetupInstaller -Version '2020.2.1f1' -Components 'Windows,UWP,UWP_IL2CPP'
Install-UnitySetupInstance -Installers $Installers -Cache 'C:\Windows\Temp' -Verbose
```

And this is the output from the command:

```
VERBOSE: Downloading https://download.unity3d.com/download_unity/270dd8c3da1c/Windows64EditorInstaller/UnitySetup64-2020.2.1f1.exe to C:\Windows\Temp\Installers\Unity-2020.2.1f1\UnitySetup64-2020.2.1f1.exe
VERBOSE: Skipping download because it's already in the cache: https://download.unity3d.com/download_unity/270dd8c3da1c/TargetSupportInstaller/UnitySetup-Universal-Windows-Platform-Support-for-Editor-2020.2.1f1.exe
ForEach-Object: C:\Program Files\WindowsPowerShell\Modules\UnitySetup\5.3.134\UnitySetup.psm1:790
Line |
 790 |                  $global:downloadData.Keys | ForEach-Object {
     |                                              ~~~~~~~~~~~~~~~~
     | Cannot process argument transformation on parameter 'Bytes'. Cannot convert value "2147500032" to type
     | "System.Int32". Error: "Value was either too large or too small for an Int32."
```

**Note: This only happens with versions from 2020 (2020.X.X) since I have installed multiple 2019 ones (ex: 2019.4.12f1)**

Could you please help me with this?
Regards,
Francisco Brito

**Comment by qelu** [comment]
Found an article on Unity explaining this error:

"Install sizes in Windows give the same size as the download size. The installed size should be larger since the download is compressed."

This error only occurs on the following versions:
2020.2.1f1
2020.2.0f1

Sorry about opening the issue here.
Hope this helps anyone encountering this problem.

Regards,
Francisco Brito

**Comment by jwittner** [comment]
@qelu - would love a link to the article you mentioned above. This looks like an error to me - the download size for the Windows installer is greater than the number of bytes that can fit in an Int so an overflow exception is getting thrown. We should update UnitySetup to handle that.

**Comment by jwittner** [comment]
@qelu - PR #220 fixes this issue. I was able to install Unity 2020.2.1f1 using the script you posted above and these modifications. Note: Without these changes I reproduced the same issues you were seeing. If you can test they fix things for you too I can merge these changes in.

**Comment by brunofitas** [comment]
thanks a lot @jwittner for this fix.

**Comment by jwittner** [comment]
PR was approved by @ziugy, so I merged it in. This should be fixed and is deployed as a prerelease package on the PowerShell Gallery [here](https://www.powershellgallery.com/packages/UnitySetup/5.4.139-develop).

**Comment by qelu** [comment]
Hi @jwittner!

The link I was talking about is this one: https://issuetracker.unity3d.com/issues/windowsinstallerset-builder-calculates-compressed-install-sizes

Thank so much for the fix and the information.

We will try this tomorrow and let you know if it fixes the issue.

Regards

**Comment by jwittner** [comment]
Excellent! These changes are now live as release version [5.4.140](https://www.powershellgallery.com/packages/UnitySetup/5.4.140)! =)
