### ISSUE TITLE
Feature request: Add ability to install Linux-IL2CPP support

### ISSUE THREAD

**Issue by JesseTG** [microsoft/unitysetup.powershell#224]
For some time now, the Windows version of Unity has been able to target Linux via IL2CPP. This Powershell module, however, cannot install it; it just doesn't appear when running `Find-UnitySetupInstaller`. Would you be able to add support for it when you get a chance? Thank you!

**Comment by jwittner** [comment]
PR is up - if you don't mind pulling down my branch and testing that would be a huge help! Also, if you have a Mac I'd love some reassurance that I didn't break linux support there with this change.

**Comment by JesseTG** [comment]
Thanks, I'll give it a shot!
