### ISSUE TITLE
Is there functionality to actually create a new fresh project?

### ISSUE THREAD

**Issue by MostHated** [microsoft/unitysetup.powershell#226]
Hey there,
    Looking through the API, I can't quite tell, is this tool capable of creating a fresh new project, or does that have to be done first, then you can run this against the existing project? I am hoping to find a way to create a while new project so that I can add some steps into the setup before the project is actually launched in the editor, as it does with the Unity hub. There is no chance to add a script before the editor fires up.

Thanks,
-MH

**Comment by jwittner** [comment]
Yeah, one can use `Start-UnityEditor -CreateProject <projectName>` to create a new project. It uses the [supported ](https://docs.unity3d.com/Manual/CommandLineArguments.html)`-createProject` flag and will make a project in a new folder called `<projectName>`. =)
