### ISSUE TITLE
Unable to identify installation of 2021.3.6f1 due to duplicate keys in modules.json

### ISSUE THREAD

**Issue by redwyre** [microsoft/unitysetup.powershell#237]
```
PS C:\Users\Administrator> Test-UnitySetupInstance -version 2021.3.6f1
WARNING: Cannot convert the JSON string because a dictionary that was converted from the string contains the duplicated
 keys 'preSelected' and 'preselected'.
False
```

The `modules.json` of 2021.3.6f1 contains keys called "preselected" and "preSelected", which from the message above seems to causing issues with it detecting the instance.

I've also posted an issue on the unity forum: https://forum.unity.com/threads/modules-json-has-duplicate-preselected-and-preselected-values-in-2021-3-6f1.1311489/

**Comment by bdovaz** [comment]
You should have posted it in the Unity hub subforum, where you have posted it, it is likely to be ignored.

**Comment by jwittner** [comment]
Hit this today and made a PR to work around the duplicate key issue.
