### ISSUE TITLE
QA "p" releases are not being found

### ISSUE THREAD

**Issue by NullEntity** [Microsoft/unitysetup.powershell#35]
```
PS C:\Users\bryce> Find-UnitySetupInstaller -Version 2017.3.0p4 -Components Setup
Could not find archives for Unity version 2017.3.0p4
At C:\Users\bryce\OneDrive\Documents\WindowsPowerShell\Modules\UnitySetup\2.1.43\UnitySetup.psm1:204 char:9
+         throw "Could not find archives for Unity version $Version"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...sion 2017.3.0p4:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find archives for Unity version 2017.3.0p4
```

It seems to fail on any "p" releases. I got the version numbers from the Patch Releases page. Other release types seem to be working correctly.

**Comment by NullEntity** [comment]
It looks to me like this line should be `-ne`. I changed it in a local copy and it seems to find the version info properly now.
https://github.com/Microsoft/unitysetup.powershell/blob/develop/UnitySetup/UnitySetup.psm1#L199

**Comment by jwittner** [comment]
Thanks! There was another issue in there too. PR is up for moving fix into develop. Next release to master should happen this week.
