### ISSUE TITLE
Find-UnitySetupInstaller can't find Unity 2017.1.2p3 Mac component

### ISSUE THREAD

**Issue by NullEntity** [Microsoft/unitysetup.powershell#43]
I'm trying to install the Mac component for Unity 2017.1.2p3. Finding the Mac installer returns nothing, including no error.

```
PS C:\Users\bryce> Find-UnitySetupInstaller -Version 2017.1.2p3 -Components Mac
PS C:\Users\bryce> Find-UnitySetupInstaller -Version 2017.1.2p3 -Components Setup


ComponentType : Setup
Version       : 2017.1.2p3
Length        : 541722008
LastModified  : 11/21/2017 5:27:22 AM
DownloadUrl   : https://beta.unity3d.com/download/249a06fbaf10/Windows64EditorInstaller/UnitySetup64-2017.1.2p3.exe
```
I downloaded the component through the Download Assistant and sniffed the component url: http://download.unity3d.com/download_unity/249a06fbaf10/TargetSupportInstaller/UnitySetup-Mac-Support-for-Editor-2017.1.2p3.exe

**Comment by jwittner** [comment]
Interesting, it looks like that component is under a different host from 'Setup' - that's going to make things hard to discover. I'm thinking we can wedge in a check against this explicit host for any missing components. Have you tried finding the Mac component for other versions of unity?

**Comment by jwittner** [comment]
I'm also seeing this fail for 2017.3.0f3 - looks like both UWP IL2CPP and Mac use a different host:

https://netstorage.unity3d.com/unity/a9f86dcd79df/TargetSupportInstaller/UnitySetup-UWP-IL2CPP-Support-for-Editor-2017.3.0f3.exe
https://netstorage.unity3d.com/unity/a9f86dcd79df/TargetSupportInstaller/UnitySetup-Mac-Support-for-Editor-2017.3.0f3.exe

Setup, and all the other components reside at: https://download.unity3d.com/download_unity/a9f86dcd79df/*

**Comment by jwittner** [comment]
I'm thinking I'll create a list of known url bases and look for components at all of those for every version.

**Comment by jwittner** [comment]
@NullEntity - Always interested in feedback about real use cases - would love to know what problems you're using UnitySetup for! 😀

**Comment by NullEntity** [comment]
@jwittner I'm working on automating builds in a docker container. UnitySetup is making creating the base image a breeze. I'll probably make a blog and post some code once I'm finished with it!

**Comment by jwittner** [comment]
I would be really excited to know if you get that to work! Unity.exe failed to launch for me in all base windows images (core, nano, etc) when I was trying for the same thing - that was over a year ago though.

**Comment by jwittner** [comment]
Looks like the beta versions have a slightly different naming scheme for the mac components:

TargetSupportInstaller/UnitySetup-Mac-Support-for-Editor- vs.
TargetSupportInstaller/UnitySetup-Mac-Mono-Support-for-Editor-

**Comment by NullEntity** [comment]
@jwittner @derekfreed can you also include throwing an error if a requested component isn't found to the scope of this fix? For the example from my OP, I'd like an error if I request a Mac component installer and the command can't find one.

**Comment by jwittner** [comment]
Great idea @NullEntity - I've created an issue with a proposed solution: #54

**Comment by jwittner** [comment]
@NullEntity - #54 is now closed and available in the [develop prerelease build](https://www.powershellgallery.com/packages/UnitySetup/3.0.65-develop). Use the WarningAction as 
```
Find-UnitySetupInstaller -Version 2018.1.0b9 -Components Setup,Mac,Documentation -WarningAction Stop
```
to fail if any component is missing.
