### ISSUE TITLE
Running Install Script Multiple Times Fails Installing Any

### ISSUE THREAD

**Issue by Ziugy** [Microsoft/unitysetup.powershell#59]
Running a command like `Find-UnitySetupInstaller -Version '2017.1.2f1' | Install-UnitySetupInstance` and `Find-UnitySetupInstaller -Version '2017.1.1p1' | Install-UnitySetupInstance` at the same time was causing issues with both versions being unable to install properly.

Both Unity install folders end up looking like Unity projects. Which was quite weird.
<img width="282" alt="capture" src="https://user-images.githubusercontent.com/6968091/36799108-32c7308c-1c61-11e8-8a10-9309095e2a62.PNG">

Suggested to allow for downloading all the setup files in parallel and / or up front. Lock installation to only a single one at a time.

**Comment by Ziugy** [comment]
Edit: Install issue looks to be caused by this: https://github.com/Microsoft/unitysetup.powershell/issues/60

I assume there's still reason to not install multiple versions at the same time. Keeping this issue around.

**Comment by jwittner** [comment]
Closing instead of assuming an issue persists.
